# Generated by Django 3.1.6 on 2021-04-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_testing',
        ),
    ]
