# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('is_rate_limited', models.BooleanField(default=False)),
                ('rate_limit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
                ('is_alive', models.BooleanField(default=True)),
                ('n_used', models.IntegerField(default=0)),
                ('load_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
