# Generated by Django 3.1.6 on 2021-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210503_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingThreadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_threads', models.IntegerField(default=64)),
                ('offset_param', models.IntegerField(default=6400)),
            ],
        ),
    ]
