# Generated by Django 3.1.6 on 2021-09-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parsingthreadcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingthreadcount',
            name='savers_count_division_param',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='parsingthreadcount',
            name='savers_count_max_threads',
            field=models.IntegerField(default=8),
        ),
    ]
