# Generated by Django 3.1.6 on 2022-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_useragent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxiesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_n_used', models.IntegerField(default=10)),
            ],
        ),
    ]
