# Generated by Django 3.1.6 on 2022-03-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_proxiessettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProxiesSettings',
            new_name='ProxiesSetting',
        ),
    ]
