# Generated by Django 3.1.6 on 2022-09-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220326_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
