# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_url', models.CharField(max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_url', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[[0, 'Ошибка'], [1, 'Выполняется'], [2, 'Завершено']])),
                ('error', models.TextField(blank=True, null=True)),
                ('artist_url', models.CharField(max_length=100)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('related_count', models.IntegerField(blank=True, null=True)),
                ('listens', models.IntegerField()),
                ('n_releases', models.IntegerField(default=5)),
                ('last_days', models.IntegerField(default=60)),
                ('median_days', models.IntegerField(default=60)),
                ('recurse', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
