# Generated by Django 3.1.6 on 2021-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0002_auto_20210404_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='card_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='group_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='artist_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='artist_url',
            field=models.TextField(),
        ),
    ]
