# Generated by Django 3.1.6 on 2021-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0003_auto_20210406_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='listens',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='related_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
