# Generated by Django 3.1.6 on 2021-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0004_auto_20210503_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='listens',
        ),
        migrations.AddField(
            model_name='scanner',
            name='listens_max',
            field=models.BigIntegerField(default=75000),
        ),
        migrations.AddField(
            model_name='scanner',
            name='listens_min',
            field=models.BigIntegerField(default=25000),
        ),
    ]
