# Generated by Django 3.1.6 on 2021-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0005_auto_20210504_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='status',
            field=models.IntegerField(choices=[[0, 'Ошибка'], [1, 'Выполняется'], [2, 'Завершено'], [3, 'Ожидает очереди'], [4, 'Отменено']]),
        ),
    ]
