# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_date', models.DateTimeField()),
                ('owner_id', models.IntegerField()),
                ('audio_id', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('chart_position', models.IntegerField(blank=True, null=True)),
                ('post_owner_id', models.IntegerField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('savers_count', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('doubles', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[[0, 'Ошибка'], [1, 'Выполняется'], [2, 'Завершено'], [3, 'Ожидает очереди']], default=3)),
                ('error', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=100)),
                ('param', models.TextField(blank=True, null=True)),
                ('count_only', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('savers_count', models.IntegerField(blank=True, null=True)),
                ('audios_count', models.IntegerField(blank=True, null=True)),
                ('result_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
