# Generated by Django 3.1.6 on 2021-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20210406_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='audience_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='joins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='listens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='post_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='post_owner',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='reach',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='saves',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='savers_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='audience_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cabinet_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='client_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fake_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='group_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='joins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='listens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reach',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='saves',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='listens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.BigIntegerField(),
        ),
    ]
