# Generated by Django 3.1.6 on 2021-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210503_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='retarget_exclude',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retarget_save_negative_id',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retarget_save_positive_id',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retarget_save_seen_id',
            field=models.TextField(blank=True, default=0),
        ),
    ]
