# Generated by Django 3.1.6 on 2021-10-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20211010_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='retarget_save_negative_id',
            new_name='retarget_save_negative',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='retarget_save_positive_id',
            new_name='retarget_save_positive',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='retarget_save_seen_id',
            new_name='retarget_save_seen',
        ),
    ]
