# Generated by Django 3.1.6 on 2021-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20211010_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='automate',
            name='max_cpm',
            field=models.IntegerField(default=120),
        ),
    ]
