# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('grabbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabbers', to='users.user'),
        ),
        migrations.AddField(
            model_name='audio',
            name='posts',
            field=models.ManyToManyField(related_name='audios', to='grabbers.Post'),
        ),
    ]
