# Generated by Django 3.1.6 on 2021-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbers', '0003_auto_20210406_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='audio',
            name='owner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='audio',
            name='savers_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabber',
            name='posts_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='listens',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='reposts',
            field=models.BigIntegerField(),
        ),
    ]
