# Generated by Django 3.1.6 on 2021-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbers', '0004_auto_20210503_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabber',
            name='group_ava',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabber',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabber',
            name='status',
            field=models.IntegerField(choices=[[0, 'Ошибка'], [1, 'Выполняется'], [2, 'Завершено'], [3, 'Ожидает очереди'], [4, 'Отменено']]),
        ),
    ]
