# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('analyzers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzers', to='users.user'),
        ),
    ]
