# Generated by Django 3.1.6 on 2021-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210503_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[[0, 'Ошибка'], [1, 'Выполняется'], [2, 'Завершено'], [3, 'Ожидает очереди'], [4, 'Отменено']])),
                ('error', models.TextField(blank=True, null=True)),
                ('n_last', models.BigIntegerField(default=30)),
                ('type', models.TextField(choices=[['tracks', 'Треки'], ['artists', 'Артисты']])),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_audios_parsers', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('share', models.FloatField()),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users_audios.parser')),
            ],
        ),
    ]
