# Generated by Django 3.1.6 on 2021-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_audios', '0002_parser_user_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='share',
        ),
        migrations.AddField(
            model_name='item',
            name='share_items',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='share_users',
            field=models.FloatField(null=True),
        ),
    ]
