# Generated by Django 3.1.6 on 2021-05-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_audios', '0003_auto_20210520_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
