# Generated by Django 3.1.6 on 2021-04-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service', models.CharField(choices=[['am', 'Apple Music'], ['vk', 'VK+BOOM'], ['ok', 'OK+BOOM'], ['dz', 'DEEZER'], ['it', 'iTunes'], ['ms', 'Mooscle'], ['sz', 'Shazam'], ['yt', 'YouTube'], ['ym', 'Яндекс.Музыка'], ['zv', 'СберЗвук'], ['sp', 'Spotify']], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[['am', 'Apple Music'], ['vk', 'VK+BOOM'], ['ok', 'OK+BOOM'], ['dz', 'DEEZER'], ['it', 'iTunes'], ['ms', 'Mooscle'], ['sz', 'Shazam'], ['yt', 'YouTube'], ['ym', 'Яндекс.Музыка'], ['zv', 'СберЗвук'], ['sp', 'Spotify']], max_length=20)),
                ('date', models.DateTimeField()),
                ('current', models.IntegerField()),
                ('previous', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='charts.chart')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('has_cover', models.BooleanField(default=False)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('has_distributor', models.BooleanField(default=False)),
                ('distributor', models.CharField(blank=True, max_length=100, null=True)),
                ('positions', models.ManyToManyField(related_name='track', to='charts.Position')),
            ],
        ),
    ]
