# Generated by Django 3.1.6 on 2021-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='distributor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.TextField(),
        ),
    ]
